// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpOeZwgyRF6hufr1gr9E_6t_z8oAn-f_I',
    appId: '1:996146573956:web:54660d6502d2cfbb4588d1',
    messagingSenderId: '996146573956',
    projectId: 'recorder-app-3fffd',
    authDomain: 'recorder-app-3fffd.firebaseapp.com',
    storageBucket: 'recorder-app-3fffd.firebasestorage.app',
    measurementId: 'G-R102H0LHEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv59OYjWKVewxADWEgKyXiWilYTfeoUl0',
    appId: '1:996146573956:android:a28a371d0196853c4588d1',
    messagingSenderId: '996146573956',
    projectId: 'recorder-app-3fffd',
    storageBucket: 'recorder-app-3fffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWNR86vGPcIXGU7ks7Mrcu-DOAf-DOWWQ',
    appId: '1:996146573956:ios:569c359232da07934588d1',
    messagingSenderId: '996146573956',
    projectId: 'recorder-app-3fffd',
    storageBucket: 'recorder-app-3fffd.firebasestorage.app',
    iosBundleId: 'com.example.recorderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWNR86vGPcIXGU7ks7Mrcu-DOAf-DOWWQ',
    appId: '1:996146573956:ios:569c359232da07934588d1',
    messagingSenderId: '996146573956',
    projectId: 'recorder-app-3fffd',
    storageBucket: 'recorder-app-3fffd.firebasestorage.app',
    iosBundleId: 'com.example.recorderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpOeZwgyRF6hufr1gr9E_6t_z8oAn-f_I',
    appId: '1:996146573956:web:29c78c6175051f504588d1',
    messagingSenderId: '996146573956',
    projectId: 'recorder-app-3fffd',
    authDomain: 'recorder-app-3fffd.firebaseapp.com',
    storageBucket: 'recorder-app-3fffd.firebasestorage.app',
    measurementId: 'G-PZ3TDS8LZ3',
  );
}
